language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: HpDfHIXK8LfvKWLJALBleZhbess7mz0Hn2y3sx+Li+qURiqXk9cmOBQbMnVJRctAcTC/l4ZJRlvAoNAs1OuHVEiuICM9gzd4ORjz0tLmlfvZm80Vk8ABRUSic7gxn5kckGZ8jhS638Q2karBgBv5J6kvfNOvlqbNb4Q+ymrZ7CM2/Lwp/z+2Rdym7Fy735BpSMmqNuG5RtgPJlOt6WAc4215u49/BU22DmerOJogiyWvL1Q0Oo0VdylPaFT2M7SnwCJtCL1bF6qDCyF9umbglSLIgUtV+aq+f71AAJYgpNJDpS2wTDdjtrq81ZOJ+FJw4ukSkd2ZeUl/oZFtVswB6vHhfpSFaMgLk437j54XOzWzOxtFBuQxmp3AbGRssYBg/TTpdC4+5q2/+Y99Y2gL2RL+xCNotKojjIuDetXd4EoYVEV65IaFrvyVYkP4EN9kVS2S4a9bRKoUvKYKgBuom6mODF+n2Hsvt5E2MsmqiFvRtBK9XQmnr+P/N8BEMadLSGKymRsJaFOahCQvNE4S3uUtfcdnAOchUKZAxiPBof6qgUUpsyvjzHA4UzGEiln/DW2n+gZH7J+AupoQUfGlKCOXlf/6tArIHwND6mDOy0GIqHwN4IQNbuZO/3ZktC40oSD8gU3vOFtJNRlGSBdxzsP3deHTagt3axxeplX2kIo=
  app: Michael-Noteful-V4
  on:
    repo: thinkful-ei26/Michael-Noteful-V4
